// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCM2hXmWJLKOFaWSpKBGzNkqvs6Ut42Nc',
    appId: '1:808431602149:web:8447fa2b02dfe0a5a8870c',
    messagingSenderId: '808431602149',
    projectId: 'moviles-project-goncha',
    authDomain: 'moviles-project-goncha.firebaseapp.com',
    storageBucket: 'moviles-project-goncha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjxdX4SAhCU1aRO0m0WY38iOxhA5eqOyo',
    appId: '1:808431602149:android:2f316a5e6f53ce6aa8870c',
    messagingSenderId: '808431602149',
    projectId: 'moviles-project-goncha',
    storageBucket: 'moviles-project-goncha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1skqnVTeGCN3iKO65c2sfpAcOnzWLwKg',
    appId: '1:808431602149:ios:8a142c6148731d8ca8870c',
    messagingSenderId: '808431602149',
    projectId: 'moviles-project-goncha',
    storageBucket: 'moviles-project-goncha.appspot.com',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1skqnVTeGCN3iKO65c2sfpAcOnzWLwKg',
    appId: '1:808431602149:ios:c4c44baf91b747b3a8870c',
    messagingSenderId: '808431602149',
    projectId: 'moviles-project-goncha',
    storageBucket: 'moviles-project-goncha.appspot.com',
    iosBundleId: 'com.example.flutterFinalProject.RunnerTests',
  );
}
