// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjbWGxFQKj8P3PJ4v4SJKs3HBu_lCDtxg',
    appId: '1:122720332753:web:ec2b27e45ee9c3b447cef0',
    messagingSenderId: '122720332753',
    projectId: 'bubbleit-57575',
    authDomain: 'bubbleit-57575.firebaseapp.com',
    storageBucket: 'bubbleit-57575.appspot.com',
    measurementId: 'G-7W7J0CKZGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoWKzBvX_wFN1pOHSX0rcXbi1B7p8LpIk',
    appId: '1:122720332753:android:8c76b8cd556b583a47cef0',
    messagingSenderId: '122720332753',
    projectId: 'bubbleit-57575',
    storageBucket: 'bubbleit-57575.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADEDxA59QVP5WLTH0Mlv0FI67UivHYDJI',
    appId: '1:122720332753:ios:526ac11d23cb7c4a47cef0',
    messagingSenderId: '122720332753',
    projectId: 'bubbleit-57575',
    storageBucket: 'bubbleit-57575.appspot.com',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADEDxA59QVP5WLTH0Mlv0FI67UivHYDJI',
    appId: '1:122720332753:ios:566ce1209cd5038047cef0',
    messagingSenderId: '122720332753',
    projectId: 'bubbleit-57575',
    storageBucket: 'bubbleit-57575.appspot.com',
    iosBundleId: 'com.example.flutterFinalProject.RunnerTests',
  );
}
